import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/theme/app_spacing.dart';
import '../../../core/widgets/app_button.dart';
import '../../../core/widgets/app_card.dart';
import '../../../core/widgets/app_scaffold.dart';
import '../../../core/widgets/responsive_center.dart';
import '../../../domain/entities/word.dart';
import '../../../domain/entities/word_explanation.dart';
import '../../../providers/explanation_provider.dart';

/// Dedicated explanation view for a single word: the word/pronunciation/
/// part of speech are shown instantly from local data, while meaning,
/// common uses, an example sentence, and a short story are generated by
/// [ExplanationService] with their own loading/error/retry handling — an
/// AI hiccup here never touches the practice screen underneath.
class ExplanationScreen extends ConsumerWidget {
  const ExplanationScreen({required this.word, super.key});

  final Word word;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final contentAsync = ref.watch(explanationContentProvider(word));

    return AppScaffold(
      title: 'Explain this word',
      body: ResponsiveCenter(
        builder: (context, isWide) {
          return SingleChildScrollView(
            padding: EdgeInsets.symmetric(
              horizontal: isWide ? AppSpacing.xl : 0,
              vertical: AppSpacing.md,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _WordHeader(word: word, theme: theme),
                const SizedBox(height: AppSpacing.xl),
                Semantics(
                  liveRegion: true,
                  child: contentAsync.when(
                    loading: () => const _LoadingSection(),
                    error: (error, stackTrace) => _ErrorSection(
                      message: error.toString(),
                      onRetry: () =>
                          ref.invalidate(explanationContentProvider(word)),
                    ),
                    data: (content) => _ContentSections(content: content),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}

class _WordHeader extends StatelessWidget {
  const _WordHeader({required this.word, required this.theme});

  final Word word;
  final ThemeData theme;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(word.headword, style: theme.textTheme.displayLarge),
        if (word.phoneticSpelling != null)
          Padding(
            padding: const EdgeInsets.only(top: AppSpacing.xs),
            child: Text(
              word.phoneticSpelling!,
              style: theme.textTheme.bodyMedium,
            ),
          ),
        const SizedBox(height: AppSpacing.xs),
        Text(
          '${word.partOfSpeech.label} · ${word.cefrLevel.label}',
          style: theme.textTheme.labelLarge,
        ),
      ],
    );
  }
}

class _LoadingSection extends StatelessWidget {
  const _LoadingSection();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: AppSpacing.xxl),
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: AppSpacing.md),
            Text('Generating an explanation…'),
          ],
        ),
      ),
    );
  }
}

class _ErrorSection extends StatelessWidget {
  const _ErrorSection({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppSpacing.xl),
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.cloud_off_rounded,
              size: 40,
              color: theme.colorScheme.error,
            ),
            const SizedBox(height: AppSpacing.md),
            Text(
              message,
              textAlign: TextAlign.center,
              style: theme.textTheme.bodyLarge,
            ),
            const SizedBox(height: AppSpacing.lg),
            AppButton(
              label: 'Retry',
              icon: Icons.refresh_rounded,
              variant: AppButtonVariant.outlined,
              onPressed: onRetry,
            ),
          ],
        ),
      ),
    );
  }
}

class _ContentSections extends StatelessWidget {
  const _ContentSections({required this.content});

  final WordExplanation content;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _Section(
          title: 'Meaning',
          child: Text(content.meaning, style: theme.textTheme.bodyLarge),
        ),
        const SizedBox(height: AppSpacing.md),
        _Section(
          title: 'Common uses',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: content.commonUses
                .map(
                  (use) => Padding(
                    padding: const EdgeInsets.only(bottom: AppSpacing.xs),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('•  ', style: theme.textTheme.bodyLarge),
                        Expanded(
                          child: Text(use, style: theme.textTheme.bodyLarge),
                        ),
                      ],
                    ),
                  ),
                )
                .toList(),
          ),
        ),
        const SizedBox(height: AppSpacing.md),
        _Section(
          title: 'Example sentence',
          child: Text(
            content.exampleSentence,
            style: theme.textTheme.bodyLarge?.copyWith(
              fontStyle: FontStyle.italic,
            ),
          ),
        ),
        const SizedBox(height: AppSpacing.md),
        _Section(
          title: 'Short story',
          child: Text(content.shortStory, style: theme.textTheme.bodyLarge),
        ),
      ],
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: theme.textTheme.titleMedium),
          const SizedBox(height: AppSpacing.xs),
          child,
        ],
      ),
    );
  }
}
